project_id = "wtdjlfwzakgwdallsiii"

[auth.mfa]
totp.issuer = "ANTBogura"

[functions.send-sms]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.update-user-role]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.cleanup-orphan-users]
verify_jwt = false
